### ISSUE TITLE
Using any element as the dropdown-toggle

### ISSUE THREAD

**Issue by tpluscode** [nik-christou/lit-element-bootstrap#13]
I would like to be able to use any custom element as the `dropdown-toggle`:

```html
<bs-dropdown>
  <canvas-button dropdown-toggle label="Operations" color="aqua"></canvas-button>
  <bs-dropdown-menu down x-placement="bottom-start">
    <bs-dropdown-item-button title="Hello world" />
  </bs-dropdown-menu>
</bs-dropdown>
```

In the snippet above `canvas-button` is another bootstrap-styles custom element but I suppose it could be anything, including a plain, native-looking element.

**Comment by nik-christou** [comment]
Its a nice idea. Maybe the logic of what is considered a dropdown toggle element should be extracted into a separate mixin. That way any element can use it and thus removing the need to have to use the BsButtonMixin

**Comment by tpluscode** [comment]
A dropdown mixin sounds useful but it would require a more refactoring. Currently the dropdown relies on `bs-button-click` which is part of `BsButtonMixin`. Splitting the mixin in two and refactoring its usages is currently beyond my insight though

**Comment by nik-christou** [comment]
Agreed for now your solution is simple and it works without too many changes. Thank you for your time :-)
