### ISSUE TITLE
bs-nav-link target _blank by default?

### ISSUE THREAD

**Issue by daniel-sullivan** [nik-christou/lit-element-bootstrap#2]
This seems like a strange default setting especially considering that most use cases of elements is within PWA's and the like where usually a separate handler will deal with rendering link results (be it dynamically loading elements etc.)

This issue is also noticeable within the docs pages for this project where clicking on examples will open a new tab seemingly for no reason.

Otherwise thank you for an awesome library. Are you accepting pull requests? I plan to implement date / time selectors in the near future.

EDIT: If you want to make that change, I've implemented and tested it in our fork:
https://github.com/charm-jp/lit-element-bootstrap/tree/change-default-target

**Comment by nik-christou** [comment]
Hi Daniel,
Thanks for letting me know about the wrong behaviour. I do accept pull requests. I am still learning about javascript/web components so actually I am counting on them :-)

**Comment by nik-christou** [comment]
Hi Daniel,
I refactored bs-nav-link to have target set as '_self' as default. Also now it will prevent default action if the href is not set. Hope that fixes the issue.
