### ISSUE TITLE
Modal breaks on missing dependency

### ISSUE THREAD

**Issue by tpluscode** [nik-christou/lit-element-bootstrap#24]
Latest modal does not work at all with latest button because it tries to import `@lit-element-bootstrap/button/bs-close-button.js` which no longer exists

**Comment by nik-christou** [comment]
Latest modal is an alpha release so it should be using the latest @lit-element-bootstrap/button alpha release also. When modal get refactored and gets to a stable v1 release it will be using the latest stable button elements.

**Comment by tpluscode** [comment]
Fai enough
