### ISSUE TITLE
bs-close-button does not exist

### ISSUE THREAD

**Issue by dbtk2comstar** [nik-christou/lit-element-bootstrap#34]
hi 
on bsmodalheader there is an import to @lit-element-bootstrap/button/bs-close-button.js
and this js file does not exist can you upload it or change it?

**Comment by nik-christou** [comment]
The latest and stable version of @lit-element-bootstrap/button is not backwards compatible with any component in alpha version. @lit-element-bootstrap/modal is in alpha version should it should be using @lit-element-bootstrap/button with version 1.0.0-alpha.7 and the 1.0.0
