### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "*" has already been used with this registry

### ISSUE THREAD

**Issue by BernardThorpe** [nik-christou/lit-element-bootstrap#4]
First of, great work on the library! We are really enjoying using it. 

We are experiencing an issue with CustomElementRegistry definitions when using dynamic components. 

I believe changing the definition instantiation to the following will fix the issue: 

`if(!window.customElements.get('bs-*')) window.customElements.define('bs-*'', Bs*);`

This would prevent double defining elements.

We are happy to help fix the issue and create a pull request if you are open?

**Comment by nik-christou** [comment]
Hi Bernard,
I am really happy that you find the library useful. I initially made this for my own personal pert projects and as a way for to learn. I actually counting on community help & wisdom to push this to stable version, so pull request are most definitely appreciated.

**Comment by nik-christou** [comment]
Pull request was merged. closing this issue
