### ISSUE TITLE
Confusing configuration for managing expand/collapse behaviour of nav ba

### ISSUE THREAD

**Issue by amimas** [nik-christou/lit-element-bootstrap#7]
First, thanks a lot for starting this library. There are very few css libraries available right now that is built on lit-element. On top of that you've got a nice doc site available already.

I'm trying out the the responsive navigation bar following the guide here:

https://lit-element-bootstrap.dev/component/navbar

I noticed that the navigation menu is set to be expanded by default when the screen size changes. Users would have to click on the toggler icon to collapse the navigation menu. Couldn't find info in the docs on how to configure it. So, I looked at the source code here:

https://github.com/nik-christou/lit-element-bootstrap/blob/f98681f635efcd5954fd33671eaab76fdeb4d391/components/navbar/bs-navbar-collapse.js#L10-L11

I find the two properties on those lines confusing. We shouldn't need two booleans to dictate the state of expand/collapse. One variable should suffice. Either it's expanded or it's not. Furthermore, I tried to set the navigation bar to be collapsed by default as shown below, but that didn't work.

```javascript
            <bs-navbar navbar-light expand-lg class="bg-light">
              <bs-navbar-brand-link>My Site</bs-navbar-brand-link>
              <bs-navbar-toggler>
                <bs-navbar-toggler-icon></bs-navbar-toggler-icon>
              </bs-navbar-toggler>

              <bs-navbar-collapse collapsed>
                <bs-navbar-nav class="mr-auto">
                  <bs-nav-item><bs-nav-link href="https://example.com">Link 1</bs-nav-link></bs-nav-item>
                  <bs-nav-item><bs-nav-link href="http://example.com/">Link 2</bs-nav-link></bs-nav-item>
                </bs-navbar-nav>
              </bs-navbar-collapse>
            </bs-navbar>
          </bs-container>
```

**Comment by nik-christou** [comment]
Hi amimas,
You are right the navbar collapse logic was not set correctly. I refactored bs-navbar-collapse to be in collapsed mode by default. I also removed the collapsed boolean attribute.
