### ISSUE TITLE
proposal: leverage css props for color

### ISSUE THREAD

**Issue by robrez** [nik-christou/lit-element-bootstrap#8]
Hi, I just stumbled on your library; Great work! I'm evaluating this for use in a new project I'm starting

Any plans to make use of css variables to allow consumers to override theming?

For example,

using this:  https://github.com/nik-christou/lit-element-bootstrap/blob/master/theme/default-theme-css.js#L20

in here: https://github.com/nik-christou/lit-element-bootstrap/blob/master/components/button/css/bs-button-primary-css.js#L8

**Comment by nik-christou** [comment]
Hi robrez,
Thanks for reporting the issue. Keep it up :-)
I just refactored the css files for the buttons to use CSS custom properties. Now by default the values for primary, secondary etc will be used if present. If the variables are not set, then they are set via javascript to default values. In case you want to override the default value just set the specific variable. For example to override the background color use --btn-bg-color

**Comment by robrez** [comment]
fantastic! thanks

btw - are you on the polymer slack? it's a great place to engage the webComponent's community... you should click the [join slack link](https://lit-element.polymer-project.org/guide/community) if not!

a lot of folks have interest in bootstrap wc.... i think we could do some great work if we all joined forces.  i've been doing my own research [over here](https://github.com/robrez/bootstrap-modules) and have linked your repo as well as some others. I have to say, your work here is the most complete/correct initiative i've seen so far

**Comment by nik-christou** [comment]
Thanks for the comments it is much appreciated :-) This started as a pet project so I can learn javascript and web components. I never expected it to be used by anyone :-) Right now I am working on splitting individual components under the same npm package so users can just import what they need and not have to package everything.
